name: 🚥 Tests
on:
  push:

jobs:
  tests:
    name: 🧪 Evaluate Tests on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      # Don't cancel other OS runners if one fails.
      fail-fast: false
      matrix:
        # Put the operating systems you want to run on here.
        os: [ubuntu-latest]
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: true
      DOTNET_NOLOGO: true
    defaults:
      run:
        # Use bash shells on all platforms.
        shell: bash
    steps:
      - name: 🧾 Checkout
        uses: actions/checkout@v4

      - name: 💽 Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          global-json-file: global.json

      - name: 📦 Restore Dependencies
        run: dotnet restore

      - name: 🦺 Build Projects
        run: dotnet build # --configuration Release

      - name: 🧪 Run Tests
        run: dotnet test
